// Generated by <a href="http://scalaxb.org/">scalaxb</a>.
package TestSpec


trait Sequencable {
  val sequencableoption: Seq[scalaxb.DataRecord[TestSpec.SequencableOption]]
  val name: Option[String]
}


case class Sequence(sequencableoption: Seq[scalaxb.DataRecord[TestSpec.SequencableOption]] = Nil,
  name: Option[String] = None) extends Sequencable

trait SequencableOption

case class Click(value: String,
  similarity: Double,
  towardsTop: Option[Int] = None,
  towardsRight: Option[Int] = None) extends ImageMatchingable with SequencableOption


case class WaitForSomeImage(value: String,
  similarity: Double,
  secondsToWait: Option[Int] = None) extends ImageMatchingable with SequencableOption


case class EnterText(entertextoption: scalaxb.DataRecord[Any]) extends SequencableOption

trait EnterTextOption

case class Test(sequencableoption: Seq[scalaxb.DataRecord[TestSpec.SequencableOption]] = Nil,
  name: Option[String] = None) extends Sequencable


case class UseInput()


case class RunSequence(input: String,
  sequenceName: Option[String] = None) extends SequencableOption


trait ImageMatchingable {
  val value: String
  val similarity: Double
}


case class ImageMatching(value: String,
  similarity: Double) extends ImageMatchingable

